apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: numerico-hpa
spec:
  maxReplicas: 8
  minReplicas: 4
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: service-numerico-deploy
  targetCPUUtilizationPercentage: 50

  