kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dev-rol
  namespace: desarrollo
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]
  
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-role-binding
  namespace: desarrollo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-rol
subjects:
- kind: User
  name: prduser@ccarrenovipeoutlook.onmicrosoft.com
